channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.2
- pip:
  - mlflow==2.16.0
  - cffi==1.17.1
  - cloudpickle==3.0.0
  - lightgbm==4.1.0
  - matplotlib==3.6.0
  - numpy==1.26.4
  - pandas==1.5.3
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
